"""F1 telemetry explorer - Streamlit app.

Run locally:  streamlit run app.py
"""
from __future__ import annotations

import datetime as dt

import pandas as pd
import streamlit as st

from f1dash import analysis, plots, sources

st.set_page_config(page_title="F1 telemetry explorer", page_icon="🏎️", layout="wide")

REAL = "Real data (FastF1)"
SYNTHETIC = "Synthetic demo"


# --------------------------------------------------------------------------
# Cached loaders
# --------------------------------------------------------------------------
@st.cache_data(ttl=3600, show_spinner=False)
def cached_events(year: int) -> list[dict]:
    return sources.list_events(year)


@st.cache_resource(show_spinner=False, max_entries=2)
def cached_session(kind: str, year: int | None, round_number: int | None, session_name: str | None):
    # max_entries keeps memory in check: a loaded F1 session with telemetry is large.
    return sources.load_session(kind, year, round_number, session_name)


# --------------------------------------------------------------------------
# Sidebar: choose and load a session
# --------------------------------------------------------------------------
st.sidebar.title("F1 telemetry explorer")
source = st.sidebar.radio(
    "Data source", [REAL, SYNTHETIC], key="source",
    help="Real data is downloaded from the F1 live timing API through FastF1 and can take a minute. "
         "The synthetic demo runs instantly and needs no internet connection.",
)

request = None
if source == REAL:
    this_year = dt.date.today().year
    year = st.sidebar.selectbox("Season", list(range(this_year, 2017, -1)), key="year")
    try:
        events = cached_events(year)
    except Exception as exc:  # network problems, API changes
        events = []
        st.sidebar.error(f"Could not load the {year} calendar: {exc}")
    if events:
        event = st.sidebar.selectbox("Grand Prix", events, key="event", format_func=lambda e: f"{e['round']}. {e['name']}")
        default = event["sessions"].index("Race") if "Race" in event["sessions"] else len(event["sessions"]) - 1
        session_name = st.sidebar.selectbox("Session", event["sessions"], index=default, key="session")
        request = ("fastf1", year, event["round"], session_name)
else:
    request = ("synthetic", None, None, None)

if st.sidebar.button("Load session", type="primary", disabled=request is None, key="load"):
    with st.spinner("Loading session data. Real sessions can take a minute the first time."):
        try:
            st.session_state["data"] = cached_session(*request)
        except Exception as exc:
            st.session_state.pop("data", None)
            st.error(
                f"Could not load this session: {exc}. The F1 data service may be unavailable, "
                "or this session has no telemetry. Try another session or the synthetic demo."
            )

st.sidebar.caption(
    "Unofficial project. Not associated with Formula 1 companies. "
    "F1, FORMULA ONE and related marks are trademarks of Formula One Licensing B.V."
)

# --------------------------------------------------------------------------
# Main area
# --------------------------------------------------------------------------
data = st.session_state.get("data")
if data is None:
    st.header("Compare laps, corners and tyre strategies")
    st.write(
        "Choose a season, Grand Prix and session in the sidebar, then select **Load session**. "
        "To explore the app without downloading anything, switch the data source to the synthetic demo."
    )
    st.stop()

st.header(data.title)
if data.is_synthetic:
    st.warning("This session is generated by the app. It does not represent real cars, drivers or circuits.")

laps = data.laps
fastest = {d: analysis.fastest_lap_number(laps, d) for d in data.drivers["Driver"]}
fastest = {d: n for d, n in fastest.items() if n is not None}
best_time = {d: laps[(laps["Driver"] == d) & (laps["LapNumber"] == n)]["LapTimeSec"].iloc[0] for d, n in fastest.items()}
ordered = sorted(fastest, key=best_time.get)

selected = st.multiselect(
    "Drivers to compare (2 to 4)", ordered, default=ordered[:2], max_selections=4,
    help="Sorted by fastest lap. The comparison uses each driver's fastest valid lap.",
)
if len(selected) < 2:
    st.info("Select at least two drivers to compare their laps.")
    st.stop()

styles = plots.driver_styles(data.drivers, selected)
ref = st.selectbox("Reference driver (gaps are measured against this driver)", selected)


@st.cache_data(show_spinner="Aligning telemetry", max_entries=16)
def aligned_laps(title: str, drivers: tuple[str, ...], lap_numbers: tuple[int, ...]):
    # `title` is part of the cache key so different sessions never share entries.
    tels = {d: data.lap_telemetry(d, n) for d, n in zip(drivers, lap_numbers)}
    return analysis.align_laps(tels)


grids = aligned_laps(data.title, tuple(selected), tuple(fastest[d] for d in selected))

tab_laps, tab_map, tab_pace = st.tabs(["Lap comparison", "Track map", "Race pace and tyres"])

with tab_laps:
    table = pd.DataFrame(
        {
            "Driver": selected,
            "Lap": [fastest[d] for d in selected],
            "Time": [analysis.format_laptime(best_time[d]) for d in selected],
            "Gap to reference (s)": [round(best_time[d] - best_time[ref], 3) for d in selected],
            "Tyre": [laps[(laps["Driver"] == d) & (laps["LapNumber"] == fastest[d])]["Compound"].iloc[0].title() for d in selected],
            "Tyre age (laps)": [laps[(laps["Driver"] == d) & (laps["LapNumber"] == fastest[d])]["TyreLife"].iloc[0] for d in selected],
        }
    )
    st.dataframe(table, hide_index=True)
    st.plotly_chart(plots.telemetry_figure(grids, ref, styles), theme=None)
    st.caption(
        "Every lap is resampled onto a shared distance grid so points line up along the track. "
        "A positive gap means the driver is behind the reference at that point of the lap."
    )

with tab_map:
    left, right = st.columns(2)
    winners = analysis.minisector_winners(grids)
    with left:
        st.subheader("Fastest through each mini-sector")
        st.plotly_chart(plots.dominance_figure(grids[ref], winners, styles), theme=None)
        wins = winners["Winner"].value_counts()
        st.caption("Mini-sectors won: " + ", ".join(f"{d} {wins.get(d, 0)}" for d in selected))
    with right:
        st.subheader(f"Speed map: {ref}")
        st.plotly_chart(plots.speed_map_figure(grids[ref], ref), theme=None)

with tab_pace:
    clean = analysis.clean_race_laps(laps)
    st.caption("Clean laps only: valid, not in or out laps, and within 107% of the fastest lap. Most useful for Race and Sprint sessions.")
    if clean.empty:
        st.info("This session has no clean laps to show.")
    else:
        st.plotly_chart(plots.lap_times_figure(clean[clean["Driver"].isin(selected)], styles), theme=None)
        summary = analysis.pace_summary(clean)
        summary = summary[summary["Driver"].isin(selected)].copy()
        summary["Median"] = summary["MedianSec"].map(analysis.format_laptime)
        summary["Best"] = summary["BestSec"].map(analysis.format_laptime)
        summary["Gap to quickest median (s)"] = summary["GapSec"].round(3)
        st.dataframe(summary[["Driver", "Median", "Best", "Laps", "Gap to quickest median (s)"]], hide_index=True)
    stints = analysis.stint_table(laps)
    if not stints.empty:
        st.subheader("Tyre strategy")
        st.plotly_chart(plots.stint_figure(stints[stints["Driver"].isin(selected)], selected), theme=None)
